import '../globals.css'

export const metadata = {
  title: 'ecommer',
  description: 'Generated by Next.js',
}

export default function NoNavbarLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section>
      {children}
    </section>
  )
}
