import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SlideBar from "@/components/SlideBar";
import '../globals.css';
import SmallScreenNavBar from "@/components/SmallScreenNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce-app",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <div className="relative flex flex-col lg:flex-row">
        <div className="hidden sm:flex sm:fixed">
          <SlideBar />
        </div>
        <div id="sd" className="sm:hidden">
          <SmallScreenNavBar />
        </div>
        <div className="ml-0 sm:ml-[5rem] p-2">
          {children}
        </div>
      </div>
    </section>
  );
}
